### PR TITLE
Log pre-emptively here.

### PR DESCRIPTION
**Pull request by ralphbean**
This will be useful for debugging situations in the future.

### CODE REVIEW

**Comment by mprahl** [comment]
@ralphbean, can you make it `log.debug` instead of `log.info`? Otherwise, it's a good idea.

**Comment by ralphbean** [comment]
Well, it was `log.info` before ;)

And creating a release is a rare and important event!

**Comment by mprahl** [comment]
@ralphbean fair point. +1

**Comment by ralphbean** [comment]
Thanks Matt!

**Pull request merged**
