### PR TITLE
Omit doing long GET queries

### PR DESCRIPTION
**Pull request by hluk**
Long GET queries can generate HTTP error 414 "URI Too Long".

Passing too many filter arguments could be ineffective. Instead, do
single request (page_size=-1) to get only the required field
(fields=...) for all the data.

Related to:
https://github.com/product-definition-center/product-definition-center/issues/421

### CODE REVIEW

**Comment by hluk** [comment]
Couldn't run all tests on local machine (perhaps missing configuration for fedmsg).

Can someone verify there is performance regression?

**Comment by hluk** [comment]
Oh, forgot to mention that the tests now require pdc-client built from master branch (I fixed the MockAPI class to support some new features).

**Comment by ralphbean** [comment]
@hluk - sorry to let this sit for so long.  The tests *should* be in working shape.  Can you share some tracebacks or errors?

**Comment by hluk** [comment]
I still have issues running tests (on `develop` branch).

First problem is that README mentions `requirements.txt` but there is only `test-requirements.txt` file. 

This is what I executed to setup the environment:
```bash
mkvirtualenv pdc-updater
pip install -r test-requirements.txt
python setup.py develop
```

For some reason I get missing module `dogpile.cache` when I try to run `nosetests`. This fixes the problem:
```bash
deactivate
workon pdc-updater
```

Now I can run tests `nosetests -v`:
```
test_get_fedmsg (pdcupdater.tests.handler_tests.TestBaseHarness) ... ok
test_get_nonexistant_fedmsg (pdcupdater.tests.handler_tests.TestBaseHarness) ... ok
test_can_handle_atomic_update_push (pdcupdater.tests.handler_tests.test_atomic.TestAtomicUpdate) ... ok
test_cannot_handle_other_git_push (pdcupdater.tests.handler_tests.test_atomic.TestAtomicUpdate) ... ok
test_handle_a_push (pdcupdater.tests.handler_tests.test_atomic.TestAtomicUpdate) ... ok
test_audit_missing_one (pdcupdater.tests.handler_tests.test_compose.TestNewCompose) ... ok
test_audit_simple (pdcupdater.tests.handler_tests.test_compose.TestNewCompose) ... ok
test_can_handle_new_compose_finish (pdcupdater.tests.handler_tests.test_compose.TestNewCompose) ... ok
test_cannot_handle_fedbadges (pdcupdater.tests.handler_tests.test_compose.TestNewCompose) ... ok
test_cannot_handle_new_compose_doomed (pdcupdater.tests.handler_tests.test_compose.TestNewCompose) ... ok
test_cannot_handle_new_compose_start (pdcupdater.tests.handler_tests.test_compose.TestNewCompose) ... ok
test_handle_new_compose (pdcupdater.tests.handler_tests.test_compose.TestNewCompose) ...
```
...but at this point CPU starts to spin like crazy, so <kbd>Ctrl</kbd>+<kbd>C</kbd> and going home for today. :)

**Comment by hluk** [comment]
Oh, probably no need to keep this one anymore.

**Comment by ralphbean** [comment]
:+1:, thanks @hluk.

**Pull request closed without merging**
