### PR TITLE
Use hash instead of variant_uid for koji_tag, otherwise we hit the 50…

### PR DESCRIPTION
**Pull request by hanzz**
… characters limit for koji_tag used by Koji.

### CODE REVIEW

**Comment by mikebonnet** [comment]
This makes the tag name a lot more opaque. Maybe we could work with the Koji team to increase the size of the tag name? 50 chars seems pretty arbitrary.

**Comment by hanzz** [comment]
Yes, the tag name would not be nice anymore. You can still track it easily to particular module using PDC, but you won't be able to find out which module is building just from the list of tasks in Koji...

**Comment by ralphbean** [comment]
Merging this for now.  We have the flexibility to change it back later for the reasons @hanzz mentioned.

**Comment by mikebonnet** [comment]
Created a new Koji issue to increase the limit: https://pagure.io/koji/issue/369

**Pull request merged**
