### PR TITLE
atomic: Remove a duplicate component-groups query

### PR DESCRIPTION
**Pull request by lmacken**

### CODE REVIEW

**Comment by ralphbean** [comment]
CLUTCH!

Does this change the test suite?

**Comment by lmacken** [comment]
Nope.
```
..................................................                     
---------------------------------------------------------------------- 
Ran 50 tests in 231.274s                                               
                                                                       
OK                                                                     
```

**Comment by lmacken** [comment]
It shaved 10 seconds off of the test suite (down to 220 seconds for me)

**Comment by lmacken** [comment]
Hmm, I don't think it does... still takes 220-230 seconds for me every time.

**Comment by ralphbean** [comment]
Hm, ok.  :+1:.

**Comment by ralphbean** [comment]
FWIW, here I get:

```
(pdc-updater)❯ time $(which nosetests)                                                               pdc-updater/git/develop 
..................................................
----------------------------------------------------------------------
Ran 50 tests in 22.058s

OK
```

**Pull request merged**
